on:
  push:
    branches:
      - latest

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'sourmash-bio'
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          command: manifest
          release-type: rust

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
            sudo apt-get install --yes zlib1g-dev libbz2-dev musl musl-dev musl-tools clang libc6-dev

      - uses: Swatinem/rust-cache@v1.3.0
        if: ${{ steps.release.outputs.release_created }}
